language: nodejs

# Decrypt the service account
before_install:
  - openssl aes-256-cbc -K $encrypted_993ad442b345_key -iv $encrypted_993ad442b345_iv
    -in tvshow-rating-4800de91b3b9.json.enc -out service-account.json
    -d

before_script:
  - yarn
  - yarn build
script:
  - yarn test
deploy:
  - provider: gae
    skip_cleanup: true
    keyfile: service-account.json
    project: tvshow-rating
    version: $TRAVIS_COMMIT
    on:
      branch: master
